export const COLORS = {
  primaryColor: '#1A1B25',
  secondaryColor: '#455EFD',
  tertiaryColor: '#DFD9E2',
  textColor: '#ADAEBA',
  containerColor: '#F3F4FA',
};

export const COMPANY_SIZES = ['1-10', '10-20', '20-50', '50-100', '100+'].map(
  (a) => ({
    value: a.replace(/\s+/g, '_').toLowerCase().replace(/\'/gi, ''),
    label: a,
  }),
);

export const INDUSTRIES = [
  'Accounting ',
  'Airlines/Aviation',
  'Alternative Dispute Resolution',
  'Alternative Medicine',
  'Animation',
  'Apparel/Fashion',
  'Architecture/Planning',
  'Arts/Crafts',
  'Automotive',
  'Aviation/Aerospace',
  'Banking/Mortgage',
  'Biotechnology/Greentech',
  'Broadcast Media',
  'Building Materials',
  'Business Supplies/Equipment',
  'Capital Markets/Hedge Fund/Private Equity',
  'Chemicals',
  'Civic/Social Organization',
  'Civil Engineering',
  'Commercial Real Estate',
  'Computer Games',
  'Computer Hardware',
  'Computer Networking',
  'Computer Software/Engineering',
  'Computer/Network Security',
  'Construction',
  'Consumer Electronics',
  'Consumer Goods',
  'Consumer Services',
  'Cosmetics',
  'Dairy',
  'Defense/Space',
  'Design',
  'E-Learning',
  'Education Management',
  'Electrical/Electronic Manufacturing',
  'Entertainment/Movie Production',
  'Environmental Services',
  'Events Services',
  'Executive Office',
  'Facilities Services',
  'Farming',
  'Financial Services',
  'Fine Art',
  'Fishery',
  'Food Production',
  'Food/Beverages',
  'Fundraising',
  'Furniture',
  'Gambling/Casinos',
  'Glass/Ceramics/Concrete',
  'Government Administration',
  'Government Relations',
  'Graphic Design/Web Design',
  'Health/Fitness',
  'Higher Education/Acadamia',
  'Hospital/Health Care',
  'Hospitality',
  'Human Resources/HR',
  'Import/Export',
  'Individual/Family Services',
  'Industrial Automation',
  'Information Services',
  'Information Technology/IT',
  'Insurance',
  'International Affairs',
  'International Trade/Development',
  'Internet',
  'Investment Banking/Venture',
  'Investment Management/Hedge Fund/Private Equity',
  'Judiciary',
  'Law Enforcement',
  'Law Practice/Law Firms',
  'Legal Services',
  'Legislative Office',
  'Leisure/Travel',
  'Library',
  'Logistics/Procurement',
  'Luxury Goods/Jewelry',
  'Machinery',
  'Management Consulting',
  'Maritime',
  'Market Research',
  'Marketing/Advertising/Sales',
  'Mechanical or Industrial Engineering',
  'Media Production',
  'Medical Equipment',
  'Medical Practice',
  'Mental Health Care',
  'Military Industry',
  'Mining/Metals',
  'Motion Pictures/Film',
  'Museums/Institutions',
  'Music',
  'Nanotechnology',
  'Newspapers/Journalism',
  'Non-Profit/Volunteering',
  'Oil/Energy/Solar/Greentech',
  'Online Publishing',
  'Other Industry',
  'Outsourcing/Offshoring',
  'Package/Freight Delivery',
  'Packaging/Containers',
  'Paper/Forest Products',
  'Performing Arts',
  'Pharmaceuticals',
  'Philanthropy',
  'Photography',
  'Plastics',
  'Political Organization',
  'Primary/Secondary Education',
  'Printing',
  'Professional Training',
  'Program Development',
  'Public Relations/PR',
  'Public Safety',
  'Publishing Industry',
  'Railroad Manufacture',
  'Ranching',
  'Real Estate/Mortgage',
  'Recreational Facilities/Services',
  'Religious Institutions',
  'Renewables/Environment',
  'Research Industry',
  'Restaurants',
  'Retail Industry',
  'Security/Investigations',
  'Semiconductors',
  'Shipbuilding',
  'Sporting Goods',
  'Sports',
  'Staffing/Recruiting',
  'Supermarkets',
  'Telecommunications',
  'Textiles',
  'Think Tanks',
  'Tobacco',
  'Translation/Localization',
  'Transportation',
  'Utilities',
  'Venture Capital/VC',
  'Veterinary',
  'Warehousing',
  'Wholesale',
  'Wine/Spirits',
  'Wireless',
  'Writing/Editing',
].map((a) => ({
  value: a.replace(/\s+/g, '_').toLowerCase().replace(/\'/gi, ''),
  label: a,
}));

export const LANGUAGES = [
  {value: 'ab', label: 'Abkhaz'},
  {value: 'aa', label: 'Afar'},
  {value: 'af', label: 'Afrikaans'},
  {value: 'ak', label: 'Akan'},
  {value: 'sq', label: 'Albanian'},
  {value: 'am', label: 'Amharic'},
  {value: 'ar', label: 'Arabic'},
  {value: 'an', label: 'Aragonese'},
  {value: 'hy', label: 'Armenian'},
  {value: 'as', label: 'Assamese'},
  {value: 'av', label: 'Avaric'},
  {value: 'ae', label: 'Avestan'},
  {value: 'ay', label: 'Aymara'},
  {value: 'az', label: 'Azerbaijani'},
  {value: 'bm', label: 'Bambara'},
  {value: 'ba', label: 'Bashkir'},
  {value: 'eu', label: 'Basque'},
  {value: 'be', label: 'Belarusian'},
  {value: 'bn', label: 'Bengali'},
  {value: 'bh', label: 'Bihari'},
  {value: 'bi', label: 'Bislama'},
  {value: 'bs', label: 'Bosnian'},
  {value: 'br', label: 'Breton'},
  {value: 'bg', label: 'Bulgarian'},
  {value: 'my', label: 'Burmese'},
  {value: 'ca', label: 'Catalan; Valencian'},
  {value: 'ch', label: 'Chamorro'},
  {value: 'ce', label: 'Chechen'},
  {
    value: 'ny',
    label: 'Chichewa; Chewa; Nyanja',
  },
  {value: 'zh', label: 'Chinese'},
  {value: 'cv', label: 'Chuvash'},
  {value: 'kw', label: 'Cornish'},
  {value: 'co', label: 'Corsican'},
  {value: 'cr', label: 'Cree'},
  {value: 'hr', label: 'Croatian'},
  {value: 'cs', label: 'Czech'},
  {value: 'da', label: 'Danish'},
  {value: 'dv', label: 'Divehi; Dhivehi; Maldivian;'},
  {value: 'nl', label: 'Dutch'},
  {value: 'en', label: 'English'},
  {value: 'eo', label: 'Esperanto'},
  {value: 'et', label: 'Estonian'},
  {value: 'ee', label: 'Ewe'},
  {value: 'fo', label: 'Faroese'},
  {value: 'fj', label: 'Fijian'},
  {value: 'fi', label: 'Finnish'},
  {value: 'fr', label: 'French'},
  {
    value: 'ff',
    label: 'Fula; Fulah; Pulaar; Pular',
  },
  {value: 'gl', label: 'Galician'},
  {value: 'ka', label: 'Georgian'},
  {value: 'de', label: 'German'},
  {value: 'el', label: 'Greek, Modern'},
  {value: 'gn', label: 'Guaraní'},
  {value: 'gu', label: 'Gujarati'},
  {value: 'ht', label: 'Haitian; Haitian Creole'},
  {value: 'ha', label: 'Hausa'},
  {value: 'he', label: 'Hebrew (modern)'},
  {value: 'hz', label: 'Herero'},
  {value: 'hi', label: 'Hindi'},
  {value: 'ho', label: 'Hiri Motu'},
  {value: 'hu', label: 'Hungarian'},
  {value: 'ia', label: 'Interlingua'},
  {value: 'id', label: 'Indonesian'},
  {
    value: 'ie',
    label: 'Interlingue',
  },
  {value: 'ga', label: 'Irish'},
  {value: 'ig', label: 'Igbo'},
  {value: 'ik', label: 'Inupiaq'},
  {value: 'io', label: 'Ido'},
  {value: 'is', label: 'Icelandic'},
  {value: 'it', label: 'Italian'},
  {value: 'iu', label: 'Inuktitut'},
  {value: 'ja', label: 'Japanese'},
  {value: 'jv', label: 'Javanese'},
  {
    value: 'kl',
    label: 'Kalaallisut, Greenlandic',
  },
  {value: 'kn', label: 'Kannada'},
  {value: 'kr', label: 'Kanuri'},
  {value: 'ks', label: 'Kashmiri'},
  {value: 'kk', label: 'Kazakh'},
  {value: 'km', label: 'Khmer'},
  {value: 'ki', label: 'Kikuyu, Gikuyu'},
  {value: 'rw', label: 'Kinyarwanda'},
  {value: 'ky', label: 'Kirghiz, Kyrgyz'},
  {value: 'kv', label: 'Komi'},
  {value: 'kg', label: 'Kongo'},
  {value: 'ko', label: 'Korean'},
  {value: 'ku', label: 'Kurdish'},
  {value: 'kj', label: 'Kwanyama, Kuanyama'},
  {value: 'la', label: 'Latin'},
  {
    value: 'lb',
    label: 'Luxembourgish, Letzeburgesch',
  },
  {value: 'lg', label: 'Luganda'},
  {
    value: 'li',
    label: 'Limburgish, Limburgan, Limburger',
  },
  {value: 'ln', label: 'Lingala'},
  {value: 'lo', label: 'Lao'},
  {value: 'lt', label: 'Lithuanian'},
  {value: 'lu', label: 'Luba-Katanga'},
  {value: 'lv', label: 'Latvian'},
  {value: 'gv', label: 'Manx'},
  {value: 'mk', label: 'Macedonian'},
  {value: 'mg', label: 'Malagasy'},
  {value: 'ms', label: 'Malay'},
  {value: 'ml', label: 'Malayalam'},
  {value: 'mt', label: 'Maltese'},
  {value: 'mi', label: 'Māori'},
  {value: 'mr', label: 'Marathi (Marāṭhī)'},
  {value: 'mh', label: 'Marshallese'},
  {value: 'mn', label: 'Mongolian'},
  {value: 'na', label: 'Nauru'},
  {value: 'nv', label: 'Navajo, Navaho'},
  {value: 'nb', label: 'Norwegian Bokmål'},
  {value: 'nd', label: 'North Ndebele'},
  {value: 'ne', label: 'Nepali'},
  {value: 'ng', label: 'Ndonga'},
  {value: 'nn', label: 'Norwegian Nynorsk'},
  {value: 'no', label: 'Norwegian'},
  {value: 'ii', label: 'Nuosu'},
  {value: 'nr', label: 'South Ndebele'},
  {value: 'oc', label: 'Occitan'},
  {value: 'oj', label: 'Ojibwe, Ojibwa'},
  {
    value: 'cu',
    name:
      'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic',
  },
  {value: 'om', label: 'Oromo'},
  {value: 'or', label: 'Oriya'},
  {value: 'os', label: 'Ossetian, Ossetic'},
  {value: 'pa', label: 'Panjabi, Punjabi'},
  {value: 'pi', label: 'Pāli'},
  {value: 'fa', label: 'Persian'},
  {value: 'pl', label: 'Polish'},
  {value: 'ps', label: 'Pashto, Pushto'},
  {value: 'pt', label: 'Portuguese'},
  {value: 'qu', label: 'Quechua'},
  {value: 'rm', label: 'Romansh'},
  {value: 'rn', label: 'Kirundi'},
  {value: 'ro', label: 'Romanian, Moldavian, Moldovan'},
  {value: 'ru', label: 'Russian'},
  {value: 'sa', label: 'Sanskrit (Saṁskṛta)'},
  {value: 'sc', label: 'Sardinian'},
  {value: 'sd', label: 'Sindhi'},
  {value: 'se', label: 'Northern Sami'},
  {value: 'sm', label: 'Samoan'},
  {value: 'sg', label: 'Sango'},
  {value: 'sr', label: 'Serbian'},
  {value: 'gd', label: 'Scottish Gaelic; Gaelic'},
  {value: 'sn', label: 'Shona'},
  {value: 'si', label: 'Sinhala, Sinhalese'},
  {value: 'sk', label: 'Slovak'},
  {value: 'sl', label: 'Slovene'},
  {value: 'so', label: 'Somali'},
  {value: 'st', label: 'Southern Sotho'},
  {value: 'es', label: 'Spanish; Castilian'},
  {value: 'su', label: 'Sundanese'},
  {value: 'sw', label: 'Swahili'},
  {value: 'ss', label: 'Swati'},
  {value: 'sv', label: 'Swedish'},
  {value: 'ta', label: 'Tamil'},
  {value: 'te', label: 'Telugu'},
  {value: 'tg', label: 'Tajik'},
  {value: 'th', label: 'Thai'},
  {value: 'ti', label: 'Tigrinya'},
  {
    value: 'bo',
    label: 'Tibetan Standard, Tibetan, Central',
  },
  {value: 'tk', label: 'Turkmen'},
  {value: 'tl', label: 'Tagalog'},
  {value: 'tn', label: 'Tswana'},
  {value: 'to', label: 'Tonga (Tonga Islands)'},
  {value: 'tr', label: 'Turkish'},
  {value: 'ts', label: 'Tsonga'},
  {value: 'tt', label: 'Tatar'},
  {value: 'tw', label: 'Twi'},
  {value: 'ty', label: 'Tahitian'},
  {value: 'ug', label: 'Uighur, Uyghur'},
  {value: 'uk', label: 'Ukrainian'},
  {value: 'ur', label: 'Urdu'},
  {value: 'uz', label: 'Uzbek'},
  {value: 've', label: 'Venda'},
  {value: 'vi', label: 'Vietnamese'},
  {value: 'vo', label: 'Volapük'},
  {value: 'wa', label: 'Walloon'},
  {value: 'cy', label: 'Welsh'},
  {value: 'wo', label: 'Wolof'},
  {value: 'fy', label: 'Western Frisian'},
  {value: 'xh', label: 'Xhosa'},
  {value: 'yi', label: 'Yiddish'},
  {value: 'yo', label: 'Yoruba'},
  {value: 'za', label: 'Zhuang, Chuang'},
];
